# ==================================================================================
#
#       Copyright (c) 2022 Samsung Electronics Co., Ltd. All Rights Reserved.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#          http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
# ==================================================================================
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: kfadapter-configmap
  namespace: {{ include "common.namespace.platform" . }}
data:
  # Configuration values can be set as key-value properties
  KUBEFLOW_HOST: ml-pipeline-ui.kubeflow
  KUBEFLOW_PORT: "80"
  KF_NAMESPACE: "ric"
  KF_ADAPTER_PORT: "{{ include "common.serviceport.kfadapter.http" . }}"
  TRAININGMGR_HOST: {{ include "common.servicehost.tm.http" . }}
  TRAININGMGR_PORT: "{{ include "common.serviceport.tm.http" . }}"
  PYTHONUNBUFFERED: "0"
