# ==================================================================================
#
#       Copyright (c) 2022 Samsung Electronics Co., Ltd. All Rights Reserved.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#          http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
# ==================================================================================

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "data-extraction.fullname" . }}
  namespace: {{ include "common.namespace.platform" . }}
  labels:
    {{- include "data-extraction.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "data-extraction.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "data-extraction.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.dataextraction.image.repository }}:{{ .Values.dataextraction.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.dataextraction.image.pullPolicy }}
          env:
            - name: FS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cassandra
                  key: cassandra-password
          ports:
            - name: serviceport
              containerPort: {{ include "common.serviceport.data-extraction.http" .  }}
              protocol: TCP
          workingDir: /home/app/dataextraction
          command: ["python3"]
          args: [main.py]
          # command: ["sleep"]
          # args: [infinity]
          # livenessProbe:
          #   httpGet:
          #     path: /trainingjobs/latest
          #     port: serviceport
          # readinessProbe:
          #   httpGet:
          #     path: /trainingjobs/latest
          #     port: serviceport
          envFrom:
            - configMapRef:
                name: data-extraction-configmap
