apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  config: |
    {
    namespace: $(kfp-namespace),
    executorImage: gcr.io/ml-pipeline/argoexec:v2.7.5-license-compliance,
    containerRuntimeExecutor: $(kfp-container-runtime-executor),
    artifactRepository:
    {
        s3: {
            bucket: $(kfp-artifact-bucket-name),
            keyPrefix: artifacts,
            endpoint: leofs.$(kfp-namespace):8080,
            insecure: true,
            accessKeySecret: {
                name: mlpipeline-leofs-artifact,
                key: accesskey
            },
            secretKeySecret: {
                name: mlpipeline-leofs-artifact,
                key: secretkey
            }
        },
        archiveLogs: true
    }
    }
