kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: leofs-pvc
  namespace: {{ include "common.namespace.kubeflow" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-client
